### ISSUE TITLE
Cannot login to Trello using Google Account

### ISSUE THREAD

**Issue by mickhalsband** [appstract/trello-for-franz#1]
When trying to configure Trello, the button "Log in with Google" does nothing (see login screen below).
This is probably due to a failed popup.
Due to Trello-Google authentication I can't use Trello from Franz

![screen shot 2016-11-17 at 13 13 46](https://cloud.githubusercontent.com/assets/362708/20388985/b06c0aae-acc7-11e6-8966-ba856f5afde1.png)

**Comment by teuunn** [comment]
Hi @mickhalsband,

Can you provide some more information about your issue? Which version of Franz and OS are you running?

**Comment by phaberest** [comment]
Same here, using OSX Sierra. I'm somehow redirected again to password input after the first google login and I'm not able to continue from there
