### ISSUE TITLE
 This is necessary?

### ISSUE THREAD

**Issue by iurimattos** [appstract/trello-for-franz#2]
I want to say that greatly admire the work of open source developers because from them knowledge is shared

But seeing that the meetfranz has a plugin for trello and more (https://github.com/meetfranz/plugins) you dont need this repository.

Well, if I were you and had your knowledge, I would make a fork and try to send pull request

[]'s

**Comment by ovanschie** [comment]
Thanks for the notice.
We developed this plugin before the other one came out.

Also our version is only for notifications, with a slightly customized notification overview page.

So we just leave this here :)
